on:
  push:
    branches:
      - main
name: CI & CD
jobs:
  build-deploy:
    name: Build and Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v2
      - name: Get Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.
      - name: Build
        run: |
          npm install
          npm run build
      - name: List output files
        run: find .next/ -print
      - name: Copy files
        run: cp -r .next/ out/
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          local-dir: .next
